version: '3.8'

services:
  db:
    image: postgres:14
    container_name: escala_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: escala_musicos
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: escala_api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/escala_musicos?schema=public"
      JWT_SECRET: "secret_dev"
    command: npm run dev

volumes:
  pg_data: